// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TallerMecanica.App.Persistencia.AppRepositorios;

namespace TallerMecanica.App.Persistencia.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220923211204_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TallerMecanica.App.Dominio.Entidades.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIdentificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("TallerMecanica.App.Dominio.Entidades.Repuesto", b =>
                {
                    b.Property<int>("RepuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NombreRespuesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuRevisionRevisionId")
                        .HasColumnType("int");

                    b.HasKey("RepuestoId");

                    b.HasIndex("SuRevisionRevisionId");

                    b.ToTable("Repuestos");
                });

            modelBuilder.Entity("TallerMecanica.App.Dominio.Entidades.Revision", b =>
                {
                    b.Property<int>("RevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("EstadoAceite")
                        .HasColumnType("int");

                    b.Property<int>("EstadoFiltroAire")
                        .HasColumnType("int");

                    b.Property<int>("EstadoFiltroGasolina")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaMantenimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObservacionMantenimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuTecnicoPersonaId")
                        .HasColumnType("int");

                    b.Property<int?>("SuVehiculoVehiculoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoMantenimiento")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("RevisionId");

                    b.HasIndex("SuTecnicoPersonaId");

                    b.HasIndex("SuVehiculoVehiculoId");

                    b.ToTable("Revisiones");
                });

            modelBuilder.Entity("TallerMecanica.App.Dominio.Entidades.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehiculoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("TallerMecanica.App.Dominio.Entidades.Cliente", b =>
                {
                    b.HasBaseType("TallerMecanica.App.Dominio.Entidades.Persona");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("TallerMecanica.App.Dominio.Entidades.Tecnico", b =>
                {
                    b.HasBaseType("TallerMecanica.App.Dominio.Entidades.Persona");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaContrato")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("TallerMecanica.App.Dominio.Entidades.Repuesto", b =>
                {
                    b.HasOne("TallerMecanica.App.Dominio.Entidades.Revision", "SuRevision")
                        .WithMany("SusRepuestos")
                        .HasForeignKey("SuRevisionRevisionId");

                    b.Navigation("SuRevision");
                });

            modelBuilder.Entity("TallerMecanica.App.Dominio.Entidades.Revision", b =>
                {
                    b.HasOne("TallerMecanica.App.Dominio.Entidades.Tecnico", "SuTecnico")
                        .WithMany("SusRevisiones")
                        .HasForeignKey("SuTecnicoPersonaId");

                    b.HasOne("TallerMecanica.App.Dominio.Entidades.Vehiculo", "SuVehiculo")
                        .WithMany("SusRevisiones")
                        .HasForeignKey("SuVehiculoVehiculoId");

                    b.Navigation("SuTecnico");

                    b.Navigation("SuVehiculo");
                });

            modelBuilder.Entity("TallerMecanica.App.Dominio.Entidades.Vehiculo", b =>
                {
                    b.HasOne("TallerMecanica.App.Dominio.Entidades.Cliente", "SuPropietario")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuPropietario");
                });

            modelBuilder.Entity("TallerMecanica.App.Dominio.Entidades.Cliente", b =>
                {
                    b.HasOne("TallerMecanica.App.Dominio.Entidades.Persona", null)
                        .WithOne()
                        .HasForeignKey("TallerMecanica.App.Dominio.Entidades.Cliente", "PersonaId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TallerMecanica.App.Dominio.Entidades.Tecnico", b =>
                {
                    b.HasOne("TallerMecanica.App.Dominio.Entidades.Persona", null)
                        .WithOne()
                        .HasForeignKey("TallerMecanica.App.Dominio.Entidades.Tecnico", "PersonaId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TallerMecanica.App.Dominio.Entidades.Revision", b =>
                {
                    b.Navigation("SusRepuestos");
                });

            modelBuilder.Entity("TallerMecanica.App.Dominio.Entidades.Vehiculo", b =>
                {
                    b.Navigation("SusRevisiones");
                });

            modelBuilder.Entity("TallerMecanica.App.Dominio.Entidades.Cliente", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("TallerMecanica.App.Dominio.Entidades.Tecnico", b =>
                {
                    b.Navigation("SusRevisiones");
                });
#pragma warning restore 612, 618
        }
    }
}
